version: "3.9"
services:
  app:
    image: ghcr.io/${IMAGE_REPO}:${RELEASE_VERSION}
    restart: always
    container_name: ${APP_NAME}_app
    ports:
      - "8080"
    environment:
      VIRTUAL_HOST: ${HOST_DOMAIN}
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: ${HOST_DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      OPENAI_MODEL: ${OPENAI_MODEL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GOOGLE_APPLICATION_CREDENTIALS: "/app/googlecloud-credentials.json"
    volumes:
      - app-mydb:/app/App_Data

  app-migration:
    image: ghcr.io/${IMAGE_REPO}:${RELEASE_VERSION}
    container_name: ${APP_NAME}_app_migration
    restart: "no"
    profiles:
      - migration
    command: --AppTasks=migrate
    volumes:
      - app-mydb:/app/App_Data

volumes:
  app-mydb:

networks:
  default:
    name: nginx
    external: true
